baseURL = "http://foysalahamed.com/"
languageCode = "en-us"
title = "Foysal Ahamed | LAZYB0Y"
theme = "minimo"

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Software Engineer, TigerIT Bangladesh Limited"
title404 = "Nothing's here!"

[params.copyright]
prefix = ""
holder = "Foysal Ahamed"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.social]
github = "Lazyb0y"
facebook = "Lazyb0y"
twitter = "Lazyb0y24"
instagram = "lazyb0yex"
email = "thisisfoysal@gmail.com"
linkedin = "foysalahamed"

[params.search]
client = "lunr" # algolia / fuse / lunr

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
